"""Add nim to User model

Revision ID: ed78ee73a871
Revises: 86aa1283baff
Create Date: 2025-05-28 10:46:51.034348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed78ee73a871'
down_revision = '86aa1283baff'
branch_labels = None
depends_on = None 
 

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nim', sa.String(length=20), nullable=True))
    op.create_unique_constraint(op.f('uq_users_nim'), 'users', ['nim'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_nim'), 'users', type_='unique')
    op.drop_column('users', 'nim')
    # ### end Alembic commands ###
